services:
  - type: web
    name: crystell-backend
    env: node
    plan: free
    region: singapore
    numInstances: 1
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: PORT
        value: "10000"

  - type: web
    name: crystell-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: crystell-backend
          property: host
